[package]
name = "chip8-emu"
version = "0.1.0"
authors = ["matthew"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.19.3"
cpal = "0.13.3"
rand = "0.8.3"
